fix: avoid transpile super call
babel/babel-polyfills pull request #140
Opened 2022-08-19 05:39 UTC by sanyuan0704

Avoid super call transformation which is unespected:
```ts
class List {
  map() {
    return;
  }
}

class TreeNodeList extends List {
  constructor() {
   // In current version
   // Compiled to `_mapInstanceProperty(super)`
    super.map;
   //  Compiled to _mapInstanceProperty(_context = super).call(_context);
    super.map();
  }
}
```

2022-08-19 06:17 UTC, zloirock requested changes
Instead of `List` here can be, for example, `Iterator` or `AsyncIterator` and `.map` should be polyfilled for them.

2022-08-19 06:27 UTC, sanyuan0704 commented
> Instead of `List` here can be, for example, `Iterator` or `AsyncIterator` and `.map` should be polyfilled for them.

Okay, i just give a example.In fact, the super call transformation is unspectedly.

2022-08-19 09:38 UTC, zloirock commented
@nicolo-ribaudo I don't think that here is possible to handle getters properly without rewriting all `core-js` entries for instance methods. It's one of many limitations of the pure version.

I can add `receiver` argument to those entries, but it will be available only from a new minor version and overcomplicate the logic - it's better to think about for a new major version.

I don't know what's better - proper getters of properly polyfilled parent methods.

2022-08-19 13:18 UTC, JLHwung approved these changes
I think it is good to merge it as-is. Before this PR, we are generating invalid code. After this PR the usage is not polyfilled, not ideal but at least the output work on modern environments. We can figure out how to handle `super` later.

2022-08-19 13:18 UTC, JLHwung commented on packages/babel-plugin-polyfill-corejs3/src/index.ts
> +        if (path.isMemberExpression() && t.isSuper(path.node.object)) {
```suggestion
        if (t.isSuper(path.node.object)) {
```
`path` must be a member expression at this point.

2022-09-12 16:00 UTC, liuxingbaoyu approved these changes

2022-09-12 16:10 UTC, merged